# SPDX-FileCopyrightText: 2024 The Refinery Authors <https://refinery.tools/>
#
# SPDX-License-Identifier: EPL-2.0

[versions]
frontend = "10.0.0"
pluginPublish = "1.3.1"
shadow = "8.1.8"
sonarqube = "6.1.0.5360"
versions = "0.52.0"

[libraries]
frontend = { group = "org.siouan", name = "frontend-jdk21", version.ref = "frontend" }
pluginPublish = { group = "com.gradle.publish", name = "plugin-publish-plugin", version.ref = "pluginPublish" }
shadow = { group = "io.github.goooler.shadow", name = "shadow-gradle-plugin", version.ref = "shadow" }
sonarqube = { group = "org.sonarsource.scanner.gradle", name = "sonarqube-gradle-plugin", version.ref = "sonarqube" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
